<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'rapture\\message\\adapter\\mailgun' => '/../src/Adapter/Mailgun.php',
                'rapture\\message\\adapter\\pushbullet' => '/../src/Adapter/PushBullet.php',
                'rapture\\message\\definition\\adapterinterface' => '/../src/Definition/AdapterInterface.php',
                'rapture\\message\\definition\\messageinterface' => '/../src/Definition/MessageInterface.php',
                'rapture\\message\\message' => '/../src/Message.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd

require __DIR__ . '/../../vendor/autoload.php';
require __DIR__ . '/../../rapture-http/test/bootstrap.php';
